### ISSUE TITLE
Weekly Tasks

### ISSUE THREAD

**Issue by MrChrisW** [MrChrisW/PatchChecker#1]
### Tuesday 7/7/15
+ [x] Function to read ~~CSV~~ text file
   + [x] Read two text files.
+ [x] Format of ~~CSV~~ file for Servers/Patches
+ [x] Propagate GUICtrlCreateList (Servers/Patches) with CSV data
+ [x] OnEvent function for propagating modifying patch list when selecting a server
+ [x] Test WMI object - Pulling list of patches
+ [x] Create multi Window GUI

### Wednesday 8/7/15
+ [x] Create finalised version of GUI with buttons/options
+ [x] Function to load all patches into array for checking. - WMI object
+ [x] Separate functional modules

**Comment by MrChrisW** [comment]
On load check each server using WMI for currently installed patches
Store these in an array in memory. 

Check each array of "installed patches" against the loaded CSV file of "deployed" patches.

Propagate the ListView patch table with all "deployed" patches and modify the patch status column based on if the patch is detected in the "installed patches" array.

**Comment by MrChrisW** [comment]
Servers will be on different domains, requires different authentication for each domain.

**Comment by MrChrisW** [comment]
## TODO: Wednesday - 8/7/15
### Chris
+ [ ] Format of server CSV with domain column
+ [ ]  Determine if patch list will contain heading or can it be removed?
+ [ ]  Implement domain/user authentication into WMI function - import from INI file
+ [ ]  Create settings window for authentication details - Optional
+ [ ]  Create standard tests for functions - testing framework - Optional
+ [ ]  Click on patch list for further details, Microsoft link.
+ [ ]  Include time of patch installation on report/date report was ran

### Kerien
+ [ ]  Test WMI on EDNET again - confirm port blocking SD vs OPs center. May need to use local server
+ [ ]  Determine best format for generating a CSV based report to file - Includes all servers and list of patches installed with status
+ [ ]  Complete INI file with domain authentication details for each site. - Schools, EDNET, DET
+ [ ]  Add attribution, display on button press
+ [ ]  Create function to generate default settings.INI file if it doesn't exist.

**Comment by MrChrisW** [comment]
## TODO: Friday - 10/7/15
+ [ ]  Complete reporting function - Tick box for generating report
+ [ ]  Disable and remove old domain auth settings/nslookup

**Comment by MrChrisW** [comment]
Finally release completed https://github.com/MrChrisW/PatchChecker/releases/tag/1.0.0
